rootProject.name = "snippets-java"
include("snippets-archunit")
include("snippets-core")
include("snippets-ebean")
include("snippets-jooq")
include("snippets-jooq-codegen")
include("snippets-jackson")
include("snippets-p6spy")
include("snippets-platform")
include("snippets-spring")
include("snippets-spring-exception")
include("snippets-spring-boot-starter")
include("snippets-spring-boot-starter-springdoc")
include("snippets-spring-boot-starter-handlebars")
include("snippets-spring-boot-starter-p6spy")
include("snippets-spring-boot-starter-minio")
include("snippets-test")
include("snippets-validation")